version: "3.9"
services:
  web:
    build:
      context: .
    working_dir: /globo_challenge
    volumes:
      - .:/globo_challenge/
      - bundlerGemsCached:/usr/local/bundle
    command: bash -c "bundle install && bin/app.rb"

volumes:
  bundlerGemsCached:
