version: "3.9"
services:
  web:
    build:
      context: .
    working_dir: /zee_
    volumes:
      - .:/zee_/
      - bundlerGemsCached:/usr/local/bundle
    command: bash -c "bundle install && bin/app.rb"

volumes:
  bundlerGemsCached:
